import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import ThemeToggle from './components/ThemeToggle';
import './globals.css';

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plus-jakarta',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'CondoTrack',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={`${plusJakartaSans.variable} min-h-screen bg-background text-foreground`}
      suppressHydrationWarning
    >
      <body className="h-fit w-full text-foreground antialiased mb-20">
        <ThemeToggle />
        {children}
      </body>
    </html>
  );
}
